XPC_SERVICE_NAME="application.org.sparkleshare.SparkleShare.238836173.238837258"
HOME=""
__CFBundleIdentifier="org.sparkleshare.SparkleShare"
TMPDIR="/var/folders/rv/d9yfb1hd0z74tq7cl_cw221c0000gn/T/"
COMMAND_MODE="unix2003"
PATH="/usr/bin:/bin:/usr/sbin:/sbin"
DISPLAY="/var/run/com.apple.launchd.29lf78sNkc/org.xquartz:0"
USER="asr"
LOGNAME="asr"
SSH_AUTH_SOCK="/var/run/com.apple.launchd.YT9a6I0XZb/Listeners"
SHELL="/bin/zsh"
XPC_FLAGS="0x0"
OSLogRateLimit="64"
__CF_USER_TEXT_ENCODING="0x1F5:0x0:0x0"
GIT_SSH_COMMAND='"/usr/bin/ssh" -i "/Users/asr/Library/Application Support/org.sparkleshare.SparkleShare/ssh/2026-04-27_15h02.key" -o UserKnownHostsFile="/Users/asr/Library/Application Support/org.sparkleshare.SparkleShare/ssh/known_hosts" -o IdentitiesOnly=yes -o PasswordAuthentication=no -F /dev/null'
GIT_TERMINAL_PROMPT="0"
GIT_CONFIG_NOSYSTEM="1"
PREFIX = ""
LANG = "en_US.UTF8"
LC_ALL = en_US.UTF8
SSH_ASKPASS = "/usr/local/bin/ssh-askpass"
git ls-remote --heads "ssh://admin@nas01.fritz.box:2222/NAS/newt-qpkg.git"
