language: csharp
cache:
  directories:
    - upload
jobs:
  include:
    - stage: "Compile for Mac"
      os: osx
      before_install:
        - mkdir -p ./upload
        - brew install xamarin.mac
      script:
        - msbuild /p:Configuration=ReleaseMac SparkleShare.sln
      before_deploy:
        - mv SparkleShare/Mac/bin/ReleaseMac/SparkleShare.app ./upload/SparkleShare-macos-nightly.app
      deploy: &deploy_base
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file: ./upload/SparkleShare-macos-nightly.app‚
        skip_cleanup: true
        draft: true
        name: Nightly CI Build
        on:
          branch:
            - feature/WindowsTravisCi
          tags: false

    - stage: "Compile for linux"
      os: linux
      services:
        - docker
      before_install:
        - docker pull ubuntu:latest
      script:
        - docker build --file scripts/ci/Dockerfile --tag sparkleshare:nightly .
      before_deploy:
        - export DEPLOY_FILE=`docker run --name container sparkleshare:nightly find / -name sparkleshare*.tar.gz`
        #- mv $ {DEPLOY_FILE} sparkleshare-linux-nightly.tar.gz
        
    - stage: "Compile for Windows"
      os: windows
      mono: none
      before_install:
        # - choco install netfx-4.5.2-devpack
        # - choco install windows-sdk-8.0
        - powershell Install-WindowsFeature Net-Framework-Core
        - choco install -y wixtoolset --version=3.11.2
        - choco install tartool
        - choco install unzip
      script:
        - ./SparkleShare/Windows/build.cmd installer
      before_deploy:
        - mv ./SparkleShare/Windows/SparkleShare.msi  ./upload/SparkleShare-windows-nightly.exe
      deploy:
          <<: *deploy_base
          draft: true
          file: ./upload/SparkleShare-windows-nightly.exe‚

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/f1a1178baa78d1162385
#    on_success: change
#    on_failure: always
#    on_start: never
