<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>..\..\.\SparkleShare\Windows\Images\sparkleshare-app.ico</ApplicationIcon>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>false</DisableImplicitNuGetFallbackFolder>
    <Utf8Output>true</Utf8Output>
    <Configurations>Debug;Release;ReleaseAvalonia;DebugAvalonia</Configurations>
    <StartupObject>SparkleShare.Program</StartupObject>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.0" />
    <PackageReference Include="Avalonia.Labs.Notifications" Version="11.2.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.0" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sparkles\Sparkles.csproj" />
    <ProjectReference Include="..\..\Sparkles\Git\Sparkles.Git.csproj" />
    <None Include="Installer\SparkleShare.Installer.wixproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <!-- Tray Icons from Windows folder -->
    <None Include="..\Windows\Images\process-syncing-down.png">
      <Link>Images\process-syncing-down.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\process-syncing-idle.png">
      <Link>Images\process-syncing-idle.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\process-syncing-up.png">
      <Link>Images\process-syncing-up.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\process-syncing.png">
      <Link>Images\process-syncing.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\process-syncing-error.png">
      <Link>Images\process-syncing-error.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <!-- Tray Icons from MacOS folder --> 
    <None Include="..\Mac\Resources\process-syncing-down@2x.png">
      <Link>Images\process-syncing-down.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Mac\Resources\process-syncing-idle@2x.png">
      <Link>Images\process-syncing-idle.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Mac\Resources\process-syncing-up@2x.png">
      <Link>Images\process-syncing-up.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Mac\Resources\process-syncing@2x.png">
      <Link>Images\process-syncing.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Mac\Resources\process-syncing-error@2x.png">
      <Link>Images\process-syncing-error.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <!-- Tray Icons from Linux folder -->
    <None Include="..\Linux\Images\icons\hicolor\24x24\status\org.sparkleshare.SparkleShare-syncing-down.png">
      <Link>Images\syncing-down.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Linux\Images\icons\hicolor\24x24\status\org.sparkleshare.SparkleShare-syncing-idle.png">
      <Link>Images\process-syncing-idle.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Linux\Images\icons\hicolor\24x24\status\org.sparkleshare.SparkleShare-syncing-up.png">
      <Link>Images\syncing-up.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Linux\Images\icons\hicolor\24x24\status\org.sparkleshare.SparkleShare-syncing.png">
      <Link>Images\process-syncing.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
        <None Include="..\Linux\Images\icons\hicolor\24x24\status\org.sparkleshare.SparkleShare-syncing-error.png">
      <Link>Images\process-syncing-error.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <!-- Images - use None with CopyToOutputDirectory for file-based loading -->
    <None Include="..\Common\Images\about.png">
      <Link>Images\about.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Images\side-splash.png">
      <Link>Images\side-splash.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Images\user-icon-default.png">
      <Link>Images\user-icon-default.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Images\tutorial-slide-1.png">
      <Link>Images\tutorial-slide-1.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Images\tutorial-slide-2.png">
      <Link>Images\tutorial-slide-2.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Images\text-balloon.png">
      <Link>Images\text-balloon.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>    
    <!-- Pictures from Windows folder -->
    <None Include="..\Windows\Images\folder.png">
      <Link>Images\folder.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\tutorial-slide-3.png">
      <Link>Images\tutorial-slide-3.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\sparkleshare-app.ico">
      <Link>Images\sparkleshare-app.ico</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\sparkleshare-folder.png">
      <Link>Images\sparkleshare-folder.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Windows\Images\sparkleshare-folder.ico">
      <Link>Images\sparkleshare-folder.ico</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <!-- HTML files -->
    <EmbeddedResource Include="..\Common\HTML\day-entry.html">
      <Link>HTML\day-entry.html</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Common\HTML\event-entry.html">
      <Link>HTML\event-entry.html</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Common\HTML\event-log.html">
      <Link>HTML\event-log.html</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Common\HTML\jquery.js">
      <Link>HTML\jquery.js</Link>
    </EmbeddedResource>
    
    <!-- Icons from Linux folder for html view -->
    <None Include="..\Linux\Images\icons\hicolor\12x12\status\document-added.png">
      <Link>Images\document-added-12.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Linux\Images\icons\hicolor\12x12\status\document-deleted.png">
      <Link>Images\document-deleted-12.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Linux\Images\icons\hicolor\12x12\status\document-edited.png">
      <Link>Images\document-edited-12.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Linux\Images\icons\hicolor\12x12\status\document-moved.png">
      <Link>Images\document-moved-12.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Linux\Images\icons\hicolor\22x22\status\process-working.png">
      <Link>Images\process-working.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <!-- Presets -->
    <None Include="..\Common\Presets\github.png">
      <Link>Presets\github.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Presets\own-server.png">
      <Link>Presets\own-server.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Presets\bitbucket.png">
      <Link>Presets\bitbucket.png</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Presets\bitbucket.xml">
      <Link>Presets\bitbucket.xml</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Presets\github.xml">
      <Link>Presets\github.xml</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\Common\Presets\own-server.xml">
      <Link>Presets\own-server.xml</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Import Project="..\Common\SparkleShare.projitems" Label="Shared" />

<ItemGroup>
  <GitFiles Include="bin\Release\net9.0\git_scm\**\*" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
</ItemGroup>

<Target Name="CopyGitFiles" AfterTargets="Publish" Condition="$([MSBuild]::IsOSPlatform('Windows'))" >
  <Copy
      SourceFiles="@(GitFiles)"
      DestinationFiles="@(GitFiles->'$(PublishDir)\git_scm\%(RecursiveDir)%(Filename)%(Extension)')" />
</Target>  
<Target Name="PostBuildWindows" AfterTargets="PostBuildEvent" Condition="$([MSBuild]::IsOSPlatform('Windows'))">
  <Message Text="Running on Windows" Importance="High" />
  <Exec Command="&quot;$(ProjectDir)\os_specific\Windows\postBuild.cmd&quot; &quot;$(TargetDir)git_scm&quot;" />
</Target>
  
<Target Name="PostBuildMac" AfterTargets="Build" Condition="$([MSBuild]::IsOSPlatform('OSX'))">
  <Message Text="Running on macOS" Importance="High" />
<!--
  commented out, because execution works but build fails with : command not found. So it is done in actions
  <Exec Command="bash &quot;$(ProjectDir)/os_specific/MacOS/postBuild.sh&quot; &quot;$(TargetDir)$(AssemblyName)&quot; $(Architecture)" Condition="'$(Architecture)' != ''" />
  <Exec Command="bash &quot;$(ProjectDir)/os_specific/MacOS/postBuild.sh&quot; &quot;$(TargetDir)$(AssemblyName)&quot;" Condition="'$(Architecture)' == ''" />
-->
</Target>
<Target Name="PostBuildLinux" AfterTargets="Build" Condition="$([MSBuild]::IsOSPlatform('Linux'))">
  <Message Text="Running on Linux" Importance="High" />
  <Exec Command="&quot;$(ProjectDir)/os_specific/Linux/postBuild.sh&quot; &quot;$(TargetDir)git_scm&quot;" />
</Target>

</Project>
